# -*- coding: utf-8 -*-
"""Шпаргалка «Глаголы движения на двух страницах»."""

R = [
 ("gelmek", "to", "приходить, приезжать сюда", "bir yere gelmek  ·  -E",
  ("Eve geliyorum.", "Я иду домой.")),
 ("gitmek", "from", "идти, ехать туда", "bir yere gitmek  ·  -E",
  ("Okula gidiyorum.", "Я иду в школу.")),
 ("getirmek", "to", "приносить, привозить, приводить", "bir şeyi bir yere getirmek  ·  -E",
  ("Bana su getir.", "Принеси мне воды.")),
 ("götürmek", "from", "уносить, отвозить, отводить", "bir şeyi bir yere götürmek  ·  -E",
  ("Kitabı okula götür.", "Отнеси книгу в школу.")),
 ("almak", "to", "брать, забирать", "bir yerden almak  ·  -DEN",
  ("Çocuğu okuldan aldım.", "Я забрал ребёнка из школы.")),
 ("girmek", "to", "входить внутрь", "bir yere girmek  ·  -E",
  ("Eve girdim.", "Я вошёл в дом.")),
 ("çıkmak", "from", "выходить наружу; подниматься", "bir yerden çıkmak  ·  -DEN",
  ("Evden çıktım.", "Я вышел из дома.")),
 ("binmek", "to", "садиться в транспорт", "bir şeye binmek  ·  -E",
  ("Otobüse bindim.", "Я сел в автобус.")),
 ("inmek", "from", "выходить из транспорта; спускаться", "bir şeyden inmek  ·  -DEN",
  ("Otobüsten indim.", "Я вышел из автобуса.")),
 ("dönmek", "to", "возвращаться; поворачивать", "bir yere dönmek  ·  -E",
  ("Eve döndüm.", "Я вернулся домой.")),
 ("geçmek", "neut", "переходить, проезжать мимо", "bir yeri / bir yerden geçmek",
  ("Caddeyi geçtim.", "Я перешёл улицу.")),
 ("yürümek", "neut", "идти пешком", "yürüyerek gitmek  ·  bir yerde yürümek",
  ("Parkta yürüdük.", "Мы гуляли в парке.")),
 ("koşmak", "neut", "бежать", "bir yere doğru koşmak",
  ("Koşarak geldim.", "Я прибежал.")),
 ("sürmek", "neut", "вести, водить транспорт", "araba sürmek",
  ("Dikkatli sür.", "Веди осторожно.")),
 ("uçmak", "neut", "лететь", "bir yerden bir yere uçmak",
  ("İzmir'e uçuyorum.", "Я лечу в Измир.")),
 ("yaklaşmak", "to", "приближаться", "bir şeye yaklaşmak  ·  -E",
  ("Eve yaklaşıyoruz.", "Мы приближаемся к дому.")),
 ("uzaklaşmak", "from", "удаляться", "bir şeyden uzaklaşmak  ·  -DEN",
  ("Kıyıdan uzaklaştık.", "Мы отплыли от берега.")),
 ("varmak", "to", "прибывать, добираться", "bir yere varmak  ·  -E",
  ("İstanbul'a vardık.", "Мы прибыли в Стамбул.")),
 ("ulaşmak", "to", "достигать, добираться", "bir yere ulaşmak  ·  -E",
  ("Zirveye ulaştık.", "Мы достигли вершины.")),
 ("ayrılmak", "from", "покидать место", "bir yerden ayrılmak  ·  -DEN",
  ("Otelden ayrıldık.", "Мы выехали из отеля.")),
 ("taşınmak", "neut", "переезжать жить", "bir yere taşınmak  ·  -E",
  ("İzmir'e taşındım.", "Я переехал в Измир.")),
 ("gezmek", "neut", "осматривать, гулять", "bir yeri / bir yerde gezmek",
  ("İstanbul'u gezdik.", "Мы осмотрели Стамбул.")),
 ("dolaşmak", "neut", "бродить, обходить", "bir yerde / bir yeri dolaşmak",
  ("Sokaklarda dolaştık.", "Мы бродили по улицам.")),
 ("kaçmak", "from", "убегать", "bir yerden kaçmak  ·  -DEN",
  ("Evden kaçtı.", "Он сбежал из дома.")),
]

CHEAT = [
    ("section", "ГЛАГОЛЫ ДВИЖЕНИЯ НА ДВУХ СТРАНИЦАХ",
     "Глагол · направление · значение · управление · пример", 16.0),
    ("sp", 1),
] + [("cheat", v, k, ru, gov, ex) for (v, k, ru, gov, ex) in R[:13]] + [
    ("pb",),
    ("section", "ГЛАГОЛЫ ДВИЖЕНИЯ НА ДВУХ СТРАНИЦАХ", "Продолжение", 16.0),
    ("sp", 1),
] + [("cheat", v, k, ru, gov, ex) for (v, k, ru, gov, ex) in R[13:]] + [
    ("sp", 10),
    ("band", "ТРИ ВОПРОСА, КОТОРЫЕ РЕШАЮТ ВСЁ",
     "1. Куда направлено движение — к точке отсчёта или от неё?\n"
     "2. Где сейчас точка отсчёта — у меня, у собеседника или в месте встречи?\n"
     "3. Какой падеж требует глагол — -E, -DEN, -DE или -İ?"),
]
