# -*- coding: utf-8 -*-
"""30 типичных ошибок русскоязычных."""

M = [
    ("Anne beni çağırdı. — Gidiyorum!", "Anne beni çağırdı. — Geliyorum!",
     "Вы движетесь К тому, кто зовёт. Gidiyorum означало бы «я ухожу»."),
    ("Yarın sana gidiyorum.", "Yarın sana geliyorum.",
     "Точка отсчёта — там, где собеседник. Движение к нему — всегда gelmek."),
    ("Buraya git!", "Buraya gel!",
     "Buraya значит «сюда, к точке отсчёта». С ним работает только gelmek."),
    ("Partiye gidiyor musun?", "Partiye geliyor musun?",
     "Если говорящий сам будет на вечеринке, он спрашивает через gelmek."),
    ("Nereye geliyorsun?", "Nereye gidiyorsun?",
     "Вопрос «куда ты идёшь?» задают про движение прочь — значит, gitmek."),
    ("Nereden gidiyorsun?", "Nereden geliyorsun?",
     "«Откуда ты идёшь?» — движение в сторону говорящего: gelmek с исходным падежом."),
    ("Geliyorum eve.", "Eve geliyorum.",
     "В турецком глагол стоит в конце предложения, а цель — перед ним."),
    ("Ben okula gitiyorum.", "Ben okula gidiyorum.",
     "У gitmek перед гласным окончанием t переходит в d: gidiyorum, gideceğim, giderim."),
    ("Yarın gitecegim.", "Yarın gideceğim.",
     "Та же замена t → d плюс буква ğ: gideceğim, а не gitecegim."),
    ("Bana su götür.", "Bana su getir.",
     "Вода должна оказаться у говорящего — значит, движение к нему: getirmek."),
    ("Bu kitabı okula getir.", "Bu kitabı okula götür.",
     "Книга уедет от говорящего в школу — нужен götürmek."),
    ("Çocuğu okula getiriyorum.", "Çocuğu okula götürüyorum.",
     "Ребёнок движется от говорящего к школе. Getirmek означал бы «привожу сюда»."),
    ("Beni okuldan götür.", "Beni okuldan al.",
     "«Забери меня» — almak: объект переходит к тому, кто забирает."),
    ("Otobüsten bindim.", "Otobüse bindim.",
     "Binmek всегда требует дательного падежа: садятся «в», а не «из»."),
    ("Otobüse indim.", "Otobüsten indim.",
     "İnmek всегда требует исходного падежа: выходят «из», а не «в»."),
    ("Duraktan ineceğim.", "Durakta ineceğim.",
     "Остановка — это место выхода, поэтому местный падеж -DA, а не исходный."),
    ("Evden girdim.", "Eve girdim.",
     "Girmek — движение внутрь, цель стоит в дательном падеже."),
    ("Eve çıktım.", "Evden çıktım.",
     "Çıkmak — движение наружу, источник стоит в исходном падеже."),
    ("Üçüncü kattan çıktım.", "Üçüncü kata çıktım.",
     "Этаж здесь — цель подъёма, значит дательный падеж."),
    ("Merdivenlere çıktım.", "Merdivenlerden çıktım.",
     "Лестница — это путь, а не цель: она стоит в исходном падеже."),
    ("Dağı çıktık.", "Dağa çıktık.",
     "Гора — цель подъёма, нужен дательный падеж."),
    ("Caddeden geçtim.", "Caddeyi geçtim.",
     "«Перейти улицу» — пересечь её: винительный падеж. "
     "Исходный дал бы смысл «пройти мимо улицы»."),
    ("Yanımı geçti.", "Yanımdan geçti.",
     "«Пройти мимо» требует исходного падежа."),
    ("Okula yürüyorum.", "Okula yürüyerek gidiyorum.",
     "Нейтральный способ сказать «я хожу в школу пешком» — yürüyerek gitmek. "
     "Само yürümek отвечает на вопрос «как», а не «куда»."),
    ("Evi ayrıldım.", "Evden ayrıldım.",
     "Ayrılmak всегда идёт с исходным падежом: покидают «что-то», уходя оттуда."),
    ("Evden yaklaştım.", "Eve yaklaştım.",
     "Yaklaşmak — приближение, поэтому дательный падеж."),
    ("Evde uzaklaştım.", "Evden uzaklaştım.",
     "Uzaklaşmak — удаление, поэтому исходный падеж."),
    ("İstanbul'a gezdim.", "İstanbul'u gezdim.",
     "Gezmek не принимает дательный падеж: осматривают сам город — винительный."),
    ("İstanbul'u vardık.", "İstanbul'a vardık.",
     "Varmak означает прибытие в точку, поэтому нужен дательный падеж."),
    ("Otobüsü kaçtım.", "Otobüsü kaçırdım.",
     "Kaçmak — «убегать», kaçırmak — «упустить, опоздать». Это разные глаголы."),
]

MISTAKES = [
    ("section", "30 ТИПИЧНЫХ ОШИБОК",
     "Самые частые промахи русскоязычных — и объяснение, почему так нельзя", 19.0),
    ("p", "Каждая ошибка ниже встречается в реальной речи постоянно. "
          "Читайте не только правильный вариант, но и строку «почему»: "
          "именно она меняет привычку."),
    ("sp", 3),
] + [("mistake", i + 1, w, r, why) for i, (w, r, why) in enumerate(M)]
